# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-15 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('hora_comidai', models.TimeField(blank=True, null=True)),
                ('hora_comidaf', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'controlhoras',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_pat', models.CharField(max_length=30)),
                ('apellido_mat', models.CharField(blank=True, max_length=30)),
                ('sexo', models.CharField(blank=True, max_length=1)),
                ('fecha_nac', models.CharField(blank=True, max_length=10)),
                ('curp', models.CharField(blank=True, max_length=18)),
                ('rfc', models.CharField(blank=True, max_length=18)),
                ('nss', models.CharField(blank=True, max_length=18)),
                ('calle', models.CharField(blank=True, max_length=50)),
                ('num', models.CharField(blank=True, max_length=5)),
                ('num_int', models.CharField(blank=True, max_length=5)),
                ('cp', models.CharField(blank=True, max_length=5)),
                ('col', models.CharField(blank=True, max_length=30)),
                ('mun', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(blank=True, max_length=20)),
                ('tel_celu', models.CharField(blank=True, max_length=13)),
                ('tel_otro', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('alias', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('gerente', models.CharField(blank=True, max_length=50)),
                ('calle', models.CharField(blank=True, max_length=50)),
                ('num', models.CharField(blank=True, max_length=5)),
                ('num_int', models.CharField(blank=True, max_length=5)),
                ('cp', models.CharField(blank=True, max_length=5)),
                ('col', models.CharField(blank=True, max_length=30)),
                ('mun', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(blank=True, max_length=20)),
                ('tel', models.CharField(blank=True, max_length=13)),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Sucursal'),
        ),
        migrations.AddField(
            model_name='controlhoras',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Personal'),
        ),
    ]
