# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-25 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='nip',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
